version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install deps
          command: sudo make dev-install
      - run:
          name: Linting
          command: make format-check
      - run:
          name: Run tests
          command: make test
      - add_ssh_keys:
          fingerprints:
            - "d3:5f:9d:68:ea:12:9a:42:d3:d3:e1:db:b0:6a:fc:d2"
      - run:
        name: TEST - Create test branch on api-data # TODO: move to the deploy phase TODO: rename
        command: |
          mkdir -p ./testpr
          cd testpr
          git clone https://github.com/PokeAPI/api-data.git api-data
          cd api-data
          git checkout -b testbranch
          touch .gitkeeptestpr
          git config --global user.name "pokeapi-machine-user"
          git config --global user.email pokeapi.co@gmail.com
          git add .
          git commit -m "play: add test file"
          git push -uf origin testbranch

workflows:
  version: 2
  test:
    jobs:
      - test
