name: Deploy Kustomize k8s cluster

on:
  push:
    branches:
      - 'master'
      - 'staging'

jobs:
  create-kustomize-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          version: v0.11.1
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true
      - name: K8s Apply
        run: |
          cp Resources/k8s/kustomize/secrets/postgres.env.sample Resources/k8s/kustomize/secrets/postgres.env
          make kustomize-apply
          kubectl proxy &
          bash Resources/scripts/wait.sh http://localhost:8001/api/v1/namespaces/pokeapi/services/pokeapi/proxy/api/v2/
      - name: Set default namespace
        run: |
          kubectl config set-context --current --namespace pokeapi
      - name: Migrate and build data
        run: |
          make k8s-migrate
          make k8s-build-db
          bash Resources/scripts/wait.sh http://localhost:8001/api/v1/namespaces/pokeapi/services/pokeapi/proxy/api/v2/pal-park-area/5/
      - name: K8s Apply
        run: |
          kubectl apply -f Resources/k8s/kustomize/jobs/load-graphql.yml
          kubectl wait --timeout=120s --for=condition=complete job/load-graphql
          last_command=$(kubectl get job -o jsonpath='{.status.succeeded}' load-graphql)
          test "$last_command" -eq 1