name: kustomize

on:
  push:
    branches:
      - 'master'
      - 'staging'

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0
        with:
          version: v0.11.1
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
      - name: Test
        run: |
          kubectl cluster-info
          kubectl get storageclass standard
          cp Resources/k8s/kustomize/secrets/postgres.env.sample Resources/k8s/kustomize/secrets/postgres.env
          make kustomize-apply
          bash Resources/scripts/wait.sh http://localhost/api/v2/
          make k8s-migrate
          make k8s-build-db
          bash Resources/scripts/wait.sh http://localhost/api/v2/pal-park-area/5/
